// Generates src/ui/icon-data.ts by inlining SVGs from the Iconify API (https://icones.js.org).
// Run: node scripts/fetch-icons.mjs
//
// To try a different icon set, edit ICON_MAP — values are Iconify ids ("prefix:name"); browse
// sets at icones.js.org (e.g. solar, ph for Phosphor, lucide, tabler). The whole UI swaps in one
// re-run. The result is inlined into the committed data file, so the app keeps zero runtime deps
// and never hits the network at runtime.
import { writeFileSync } from "node:fs";

// Lucide: a clean, consistent line set (the icons inherit currentColor; each path carries its own
// stroke attributes). Editor-grade coverage of every primitive we need.
const ICON_MAP = {
  "gly-chevron": "lucide:chevron-right",
  "gly-folder": "lucide:folder",
  "gly-file": "lucide:file",
  "gly-check": "lucide:circle-check",
  "gly-flag": "lucide:flag",
  "gly-collapse-all": "lucide:chevrons-up",
  "gly-expand-all": "lucide:chevrons-down",
  // Chrome buttons + markers (were unicode/emoji).
  "gly-settings": "lucide:settings",
  "gly-home": "lucide:house",
  "gly-arrow-left": "lucide:arrow-left",
  "gly-arrow-right": "lucide:arrow-right",
  "gly-warn": "lucide:triangle-alert",
  "gly-open-editor": "lucide:square-arrow-out-up-right",
};

// Hand-drawn glyphs with no good library equivalent (status primitives). 24-unit viewBox to
// match the fetched set so they scale identically.
const CUSTOM = {
  "gly-dot": { vb: "0 0 24 24", body: `<circle cx="12" cy="12" r="4.5" fill="currentColor"/>` },
};

async function fetchIcon(id) {
  const [prefix, name] = id.split(":");
  const res = await fetch(`https://api.iconify.design/${prefix}/${name}.svg`);
  if (!res.ok) throw new Error(`${id}: HTTP ${res.status}`);
  const svg = await res.text();
  const vb = (svg.match(/viewBox="([^"]+)"/) || [])[1] || "0 0 24 24";
  const body = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>\s*$/, "")
    .trim();
  return { vb, body };
}

const out = { ...CUSTOM };
for (const [gly, id] of Object.entries(ICON_MAP)) {
  out[gly] = await fetchIcon(id);
  console.log(`  ${gly} <- ${id}`);
}

const header =
  `// GENERATED by scripts/fetch-icons.mjs — do not edit by hand.\n` +
  `// Inlined SVG bodies (currentColor, duotone) for the icon sprite; re-run the script to swap sets.\n`;
writeFileSync(
  new URL("../src/ui/icon-data.ts", import.meta.url),
  header +
    `export const ICON_DATA: Record<string, { vb: string; body: string }> = ${JSON.stringify(out, null, 2)};\n`,
);
console.log("wrote src/ui/icon-data.ts");
